
name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # We would like to use layer caching, but the directive causes the build
      # to fail with an error.
      #   https://github.com/a-robu/matter-toy/runs/990356187
      #   - uses: satackey/action-docker-layer-caching@v0.0.8
      - run: docker --version
      - run: docker build .
